Repository go-fries/fries, pull requests merged in 2024-12, with the labels that each got.

#387 build(renovate): add renovate configuration for go modules dependencies management
  renovate.json
Labels: size:S

#417 build(renovate): add renovate configuration for go modules dependenci…
  renovate.json
Labels: dependencies, size:S

#423 feat(gomod): Add test for go.mod version check
  gomod_test.go
Labels: enhancement, size:S, go

#428 update(renovate): add Go constraint 1.22.0
  renovate.json
Labels: size:XS

#457 rollback go version to 1.22
  go.mod
  go.sum
  gomod_test.go
  renovate.json
Labels: dependencies, size:M

#475 build(.github/workflows/test.yml): remove go 1.21.x version from test matrix
  .github/workflows/test.yml
  renovate.json
Labels: size:S, go

#502 refactor: Improved Prefix option to ensure compatibility with existin…
  cache/redis/store.go
  cache/redis/store_test.go
Labels: enhancement, size:S, go

#509 build(go.mod): update go version to 1.22.10
  go.mod
  gomod_test.go
  renovate.json
Labels: dependencies, size:XS, go

#512 Update README.md
  README.md
Labels: documentation, size:XS
