Repository go-fries/fries, pull requests merged in 2024-09, with the labels that each got.

#284 refactor(redis): refactor `Cmdable` to `UniversalClient`
  Makefile
  cache/README.md
  cache/redis/store.go
  cache/redis/store_test.go
  crontab/jobwrapper/mutex/redis/locker.go
  locker/redis/locker.go
  redis/manager.go
  redis/manager_test.go
Labels: size:M, go

#285 refactor(app): `interface{}` to `any`
  .golangci.yml
  cache/null_store.go
  cache/redis/store.go
  cache/repository.go
  cache/repository_test.go
  cache/store.go
  codec/json/codec_test.go
  codec/msgpack/codec_test.go
  crontab/jobwrapper/mutex/jobwrapper_test.go
  crontab/logger.go
  crontab/logger_test.go
  gorm/scopes/init_test.go
  gorm/scopes/order.go
  gorm/scopes/where.go
  helpers/helpers_test.go
  helpers/values_test.go
  hyperf/jet/README.md
  hyperf/jet/middleware/logging/README.md
  hyperf/jet/middleware/logging/logging_test.go
  hyperf/jet/middleware/timeout/timeout.go
  hyperf/jet/packer.go
  log/stack/stack.go
  log/stack/stack_test.go
  log/syslog/syslog.go
  log/writer/writer_test.go
  maps/README.md
  maps/maps_test.go
  middleware/cors/cors.go
  middleware/request/request.go
  middleware/request/request_test.go
  pagination/paginator.go
  prints/basic.go
  recovery/recovery.go
  recovery/recovery_test.go
  signal/server.go
  signal/server_test.go
  udp/README.md
  udp/server.go
  udp/server_test.go
  x/log-adapter/gorm/logger.go
Labels: size:L, go

#291 feat(middleware): added protovalidate middleware
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
  buf.gen.yaml
  buf.lock
  buf.yaml
  genproto/.gitignore
  go.mod
  go.sum
  middleware/protovalidate/README.md
  middleware/protovalidate/validator.go
  middleware/protovalidate/validator_test.go
  proto/tests/middleware/protovalidate/v1/person.proto
Labels: enhancement, size:L

#293 feat(gin): add `Middleware`
  gin/server.go
  gin/server_test.go
Labels: enhancement, size:M, go

#294 build(go): upgrade the go version of go.mod from 1.21 to 1.22
  .github/workflows/test.yml
  go.mod
Labels: size:XS, go

#295 build(go): adjust the minimum supported version of golang to 1.21
  README.md
Labels: documentation, size:XS, go

#296 feat(gin): add tracing middleware based on the OpenTelmetry specification
  gin/middleware/tracing/README.md
  gin/middleware/tracing/spanhandler.go
  gin/middleware/tracing/tracing.go
  go.mod
  go.sum
Labels: documentation, enhancement, dependencies, size:L, go

#297 fix(crontab): fix throwing an exception when an error caused by non-lock occurs
  crontab/jobwrapper/mutex/jobwrapper.go
Labels: bug, size:XS, go

#283 feat(middleware): add slow log middleware
  middleware/slowlog/slowlog.go
  middleware/slowlog/slowlog_test.go
Labels: size:L, go

#301 feat(strings): Added strings functions
  strings/strings.go
  strings/strings_test.go
Labels: enhancement, size:L, go
